name: example
description: Numeric keyboard example

version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  numeric_keyboard:
    path: ../
  bouncing_widget: ^2.0.0

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true