name: numeric_keyboard
publish_to: none
description: Flutter plugin to display a simple numeric keyboard on Android & iOS.
version: 1.0.0
homepage: https://github.com/huextrat/numeric_keyboard

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:

  bouncing_widget:
    git:
      https://github.com/jamesnicholls04/bouncing_widget

  flutter:
    sdk: flutter

  

dev_dependencies:
  flutter_test:
    sdk: flutter